### ISSUE TITLE
Is it possible to deliver multiple emails over a single SMTP connection?

### ISSUE THREAD

**Issue by brightball** [cerebris/delayed_mailhopper#3]
I'm just looking at cutting down delivery time.  Is there a way to open a single SMTP connection to send several emails at once?

**Comment by dgeb** [comment]
I'm not sure how to accomplish this within DelayedMailhopper, which relies on a one-to-one relationship between emails and delayed jobs. 

You could probably accomplish this by creating a background daemon that continually sends unsent email generated by Mailhopper, and batches it if there's more than one message to send. This would be an alternative to DelayedMailhopper, rather than an addition to it.

**Comment by brightball** [comment]
Makes sense.  Just sort of an optimization nut. :-)
