### ISSUE TITLE
Infinite loop sending emails

### ISSUE THREAD

**Issue by blahutka** [cerebris/delayed_mailhopper#6]
After creating email in controller `Partners::InvitationMailer.invite().deliver` new row is added to Emails table but

[Mailhopper](https://github.com/cerebris/mailhopper/blob/master/app/models/mailhopper/email.rb) in method `send!` after code `mail.deliver` adds second duplicit row in Emails table and this continue in loop.

``` ruby
def send!(delivery_method = nil)
  mail = Mail.new(self.content)
  mail[:bcc] = self.bcc_address unless self.bcc_address.blank?
  Base.mailer_class.wrap_delivery_behavior(mail, delivery_method || Base.default_delivery_method)
  mail.deliver # AFTER THIS CODE NEW ROW TO EMAILS TABLE IS ADDED
  self.sent_at = Time.now
  self.save!
end
```

Any idea guys?

**Comment by dgeb** [comment]
I can see how this loop could happen if you set Mailhopper's default delivery method to itself (:mailhopper) instead of the default, :smtp. Check the value of `Mailhopper::Base.default_delivery_method` to verify if this is the problem.

The [Options section of the Mailhopper README](https://github.com/cerebris/mailhopper) includes configuration instructions. If you want Mailhopper to deliver mail via :smtp, you can simply leave out this option.

Please reopen this issue if I've misdiagnosed the problem.
